services:
  database:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: keep_simple_test_db
      MYSQL_USER: keep_simple_test_user
      MYSQL_PASSWORD: keep_simple_test_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy

volumes:
  mysql_data: